### ISSUE TITLE
请问下这个要怎么添加？

### ISSUE THREAD

**Issue by ylqjgm** [MeIsReallyBa/Openwrt-sfe-flowoffload-linux-5.4#1]
不是太懂，能否告知下要如何操作呢？

**Comment by hathlife** [comment]
克隆下来以后 `shoutcut-fe`目录整个复制到`package/kernel/`里面 那两个`patch`复制到`target/linux/generic/hack-5.4`里面 再编译的时候会有两次停下来选择都按y
